# Generated by Django 4.1 on 2022-12-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartapp", "0003_albummodel_photomodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="maplist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mapName", models.CharField(max_length=60)),
                ("mapDesc", models.TextField()),
                ("mapLat", models.CharField(max_length=20)),
                ("mapLng", models.CharField(max_length=20)),
                ("mapTel", models.CharField(max_length=20)),
                ("mapAddr", models.CharField(max_length=60)),
            ],
        ),
    ]
